services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - monitoring
    ports:
      - 16686:16686

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./nservicebus.rules.txt:/etc/prometheus/nservicebus.rules.txt
    networks:
      - monitoring
    ports:
      - 9090:9090

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
      - C:\temp\otel\traces.json:/traces.json
      - C:\temp\otel\metrics.json:/metrics.json
      - C:\temp\otel\logs.json:/logs.json
    command: --config /etc/otel-collector.yaml
    networks:
      - monitoring
    ports:
      - 8889:8889
      - 4317:4317

networks:
  rabbitmq:
    driver: bridge
  monitoring: