global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'nservicebus.rules.txt'
  
scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
    - targets: ['otel-collector:8889']